### ISSUE TITLE
Allow stepwise migrations

### ISSUE THREAD

**Issue by Dr-Horv** [cam-stitt/arnold#13]
It seems it is only possible to go all the way up or down a migration lane in a folder. I would prefer if I can input how many migrations should be run. Say ./migrator up 5 or so.

**Comment by cam-stitt** [comment]
Thanks for the idea. I'll look into implementing this in `0.4.0`. I haven't used this arnold for a little while myself, but I'll try to get the next release done in the next week.

**Comment by cam-stitt** [comment]
This is going to be in 0.4.0. I've started the progress on the develop branch.

**Comment by cam-stitt** [comment]
https://github.com/cam-stitt/arnold/commit/f1273f815cf49293ecd2785acbe3e6b8002d95d8
