### ISSUE TITLE
Code and pypi version mismatch

### ISSUE THREAD

**Issue by jcsaaddupuy** [cam-stitt/arnold#16]
Hi.

I have a project which have arnold==3.8 as a dependancy.

Today, something break.

It seems that the 3.8 eggs version uploaded on pypi is in reality a 4.0 (they had been uploaded the same day) :

<img width="1117" alt="screen shot 2015-07-06 at 18 48 25" src="https://cloud.githubusercontent.com/assets/11556/8527905/a188c596-240f-11e5-82e3-e6f37843e477.png">

<img width="1124" alt="screen shot 2015-07-06 at 18 30 44" src="https://cloud.githubusercontent.com/assets/11556/8527844/4e87c0ea-240f-11e5-8cad-8a53d0ee96a9.png">

Also, the code seems not to be consistent with its version number : 

```
# installing the 0.3.8 egg
(sandbox)~/s/sandbox ❯❯❯ easy_install "arnold==0.3.8"
Searching for arnold==0.3.8
Downloading https://pypi.python.org/packages/2.7/a/arnold/arnold-0.3.8-py2.7.egg#md5=23d0231cc35730cb7d9d5ee87baf0a5d
Processing arnold-0.3.8-py2.7.egg
...
```

```python
>>> from arnold import IGNORED_FILES # should work as in 0.3.8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name IGNORED_FILES
>>> from arnold import Terminator # but this work, as in 0.4.0
>>> Terminator.IGNORED_FILES
['__init__']

# but here, the version is still 0.3.8
>>> import pkg_resources
>>> pkg_resources.require("arnold")[0].version
'0.3.8'
```

**Comment by cam-stitt** [comment]
Interesting. I'll work on getting that resolved asap.

**Comment by cam-stitt** [comment]
It was a bit of a pain to fix the release, but it should be fine now.
