### ISSUE TITLE
multiple db support

### ISSUE THREAD

**Issue by digi604** [cam-stitt/arnold#17]

**Comment by digi604** [comment]
it is currently not possible to handle more then one db ... maybe one migration folder per db would be a solution

**Comment by stas** [comment]
Using `Model._meta.database` worked for us.

**Comment by cam-stitt** [comment]
If you feel like using Model._meta isn't going to work, please feel free to contribute. I am struggling to be able to support any work for this with other commitments.

**Comment by cam-stitt** [comment]
`Model._meta.database` is the best way to achieve this.
