### ISSUE TITLE
can't add new migrations

### ISSUE THREAD

**Issue by dmead** [cam-stitt/arnold#20]
arnold lacks an argument to add a new migrations to the folder. this would make the tool really good if i could do

`arnold --new-migrations mynewmigration`

and it would add the file with proper name and number to the migrations directory

**Comment by cam-stitt** [comment]
Thanks for the suggestion.

My original intention was to not force a naming convention on the developers. I still don't feel like it's any more beneficial then someone running a `touch 001_migration` or something similar.
