### ISSUE TITLE
initialize databases in migrations

### ISSUE THREAD

**Issue by dmead** [cam-stitt/arnold#21]
so we're trying to initialize a fresh mysql install with our migrations we've written for arnold.

when we try to connect with MySQLDatabase

it never works, because MySQLDatabase is demanding that the database exists.

arnold it seems just wants to use a reference to one of these connections.

that fine, except we want to create our databases in the migrations. but to run the migrations we've got to create the database. so we're stuck.

does this make sense? are we doing something

**Comment by stas** [comment]
Normally you'd never provide a database user with privileges to create or drop a database, this is a security concern. Which brings us to the situation where you would need to have a database before running any migrations. What's the issue with creating the database beforehand manually?

**Comment by cam-stitt** [comment]
@stas is correct. You shouldn't be initiating a database within your migrations. I guess you could create a database within the configuration file, but it's not recommended.
