### ISSUE TITLE
arnold up 0 only works when at 0

### ISSUE THREAD

**Issue by jhorman** [cam-stitt/arnold#22]
Using arnold==0.4.0, running `arnold up 0` while at 13, doesn't migrate to 14. Seems to do nothing. The only time `arnold up 0` seems to work is on a fresh db, or at migration 0. The docs say

> If you pass in a count of 0, arnold will run all migrations that have not yet been run.

**Comment by cam-stitt** [comment]
Sorry I haven't been able to get to this yet. I'll try to put some time aside to work through it.

**Comment by Tuomoz** [comment]
I have this problem too. I had a look at the code and I think changing the line https://github.com/cam-stitt/arnold/blob/master/arnold/__init__.py#L152 to "end = len(filenames)" fixes the problem.

**Comment by cam-stitt** [comment]
Thanks, I'll get this sorted out this week.

**Comment by cam-stitt** [comment]
Sorry for the delay. I've had some time off.

**Comment by Tuomoz** [comment]
No problem. I've been using `arnold up 999` in the meantime.
