### ISSUE TITLE
Automatic generation of migrations

### ISSUE THREAD

**Issue by mekanix** [cam-stitt/arnold#23]
First off, I'm not sure I can ever trust automatically generated migrations, so please consider this issue a question which is: "Are you planing on adding automatic migration writer ala Django/South?" I do like the lack of work that automation provides, but I also like being forced to get to know my migration by writing them. Anyway, if you ever decide automation is the way to go, I'd love to contribute.

**Comment by cam-stitt** [comment]
My current preference is to not include automatic migration. The goal was to have a minimal tool that simply gave you a framework for getting started. I'd like to hear your thoughts though, specifically how you think it could be achieved, so please share.

**Comment by mekanix** [comment]
I haven't studied carefully, but I think Django's migrations would be the source of inspiration. The core of that system is analyzer (I don't know if that's the name they chose) which scans the current state of DB and models (there's optimizer, too, but it's not important for initial implementation). If you decide that's the way to go with this project, I would suggest studying Django solution, first. What do you think?

**Comment by cam-stitt** [comment]
I've thought through this a little more. For now, I think automatic generation of migrations is a step to far for what I want this project to achieve. Thanks for your thoughts though. If I ever change my mind, i'll let you know.
